version: '3'
services:
  web:  
    image: jlanatta/covid:latest
    command: "./bin/docker/web.sh"
    ports:
      - "${RAILS_PORT}:3000"
    links:
      - db
      - redis
    volumes:
      - /home/ubuntu/docker_data/covid/log/web:/covid/log
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: ${REDIS_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TRN_API_KEY: ${TRN_API_KEY}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
  worker:
    image: jlanatta/covid:latest
    command: ["./wait-for-it.sh", "web:3000", "--", "./bin/docker/worker.sh"]
    links:
      - db
      - redis
    volumes:
      - /home/ubuntu/docker_data/covid/log/worker:/covid/log
      - 'data_files:/data'
    environment:
      QUEUE: '*'
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: ${REDIS_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TRACKER_DATA_FILES_FOLDER: ${TRACKER_DATA_FILES_FOLDER}
      TRN_API_KEY: ${TRN_API_KEY}
  scheduler:
    image: jlanatta/covid:latest
    command: ["./wait-for-it.sh", "web:3000", "--", "./bin/docker/scheduler.sh"]
    links:
      - db
      - redis
    volumes:
      - /home/ubuntu/docker_data/covid/log/scheduler:/covid/log
      - 'data_files:/data'
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: ${REDIS_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TRACKER_DATA_FILES_FOLDER: ${TRACKER_DATA_FILES_FOLDER}
      TRN_API_KEY: ${TRN_API_KEY}
  db:
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: bm_tracker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis:latest
    ports:
      - "6379"

volumes:
  postgres: