partial_sync:
  class: ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
  queue: default
  cron: "0 * * * *"
  args:
    -
      job_class: PartialSyncJob
      job_id: #{SecureRandom.uuid}
      queue_name: default
      queue: default
full_sync:
  class: ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
  queue: default
  cron: "0 0 * * 0"
  args:
    -
      job_class: FullSyncJob
      job_id: #{SecureRandom.uuid}
      queue_name: default
      queue: default